#! /usr/bin/env ruby

$LOAD_PATH.unshift(File.expand_path("../lib", File.dirname(__FILE__)))

require 'optparse'
require 'esvg'

options = {}

OptionParser.new do |opts|
  opts.on("-c", "--config PATH", String, "Path to a config file (default: esvg.yml, config/esvg.yml)") do |path|
    options[:config_file] = path
  end
end.parse!

options[:path] = ARGV.shift

esvg = Esvg::SVG.new(options).optimize
