#! /usr/bin/env ruby

$LOAD_PATH.unshift(File.expand_path("../lib", File.dirname(__FILE__)))

require 'optparse'
require 'esvg'

options = {}

OptionParser.new do |opts|
  opts.on("-f", "--format TYPE", String, "Options: js, html (defaults to js)") do |format|
    options[:format] = format
  end

  opts.on("-o", "--output PATH", String, "Where should JS/HTML files be written, (default: current directory)") do |path|
    options[:output_path] = path
  end

  opts.on("-c", "--config PATH", String, "Path to a config file (default: esvg.yml, config/esvg.yml)") do |path|
    options[:config_file] = path
  end

  opts.on("-r", "--rails", "Use Rails defaults") do
    options[:rails] = true
  end

  opts.on("-O", "--optimize", "Optimize svgs with svgo") do |svgo|
    options[:optimize] = svgo
  end

  opts.on("-v", "--version", "Print version") do |version|
    options[:version] = true
  end

end.parse!

if options[:version]
  puts "Esvg #{Esvg::VERSION}"
else

  if path = ARGV.shift
    options[:path] = path
  end

  options[:cli] = true
  esvg = Esvg::SVG.new(options).write
end
